//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalon.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requerimiento()
        {
            this.requerimientoDetalle = new HashSet<requerimientoDetalle>();
        }
    
        public int id { get; set; }
        public string codigoRQ { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public string prioridad { get; set; }
        public Nullable<int> idCc { get; set; }
        public Nullable<int> idScc { get; set; }
        public Nullable<int> idSscc { get; set; }
        public Nullable<int> idArea { get; set; }
        public string solicitante { get; set; }
        public string comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requerimientoDetalle> requerimientoDetalle { get; set; }
    }
}
